Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAtaskTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product
    {
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        [Column("image")]
        public string Image { get; set; }
        [Column("description")]
        public string Description { get; set; }
        //[DisplayName("Category Name")]
        public Nullable<int> CID { get; set; }
    
        public virtual category category { get; set; }
    }
}

Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IAtaskTest.Models;
using System.IO;

namespace IAtaskTest.Controllers
{
    public class productsController : Controller
    {
        private IATaskDBEntities db = new IATaskDBEntities();

        // GET: products

        public ActionResult HomePage(string search)
        {
            var products = db.products.ToList();
            var categories = db.categories.ToList();
            if (!string.IsNullOrEmpty(search))
            {
                category x = db.categories
                    .Where(c => c.CName == search).FirstOrDefault<category>();
                if (x != null)
                {
                    products = db.products
                        .Where(s => s.CID == x.CID).ToList();
                }

            }
            return View(products);
            var recs = db.products.ToList();
            return View(recs);
        }

        public ActionResult Index(string search)
        {
            var products = db.products.ToList();
            var categories = db.categories.ToList();
            if (!string.IsNullOrEmpty(search))
            {
                category x = db.categories
                    .Where(c => c.CName == search).FirstOrDefault<category>();
                if (x != null)
                {
                    products = db.products
                        .Where(s => s.CID == x.CID).ToList();
                }

            }
            return View(products);
        }


        // GET: products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            ViewBag.CID = new SelectList(db.categories, "CID", "CName");
            return View();
        }

        // POST: products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Image,Description,CID")] product product, HttpPostedFileBase imgFile)
        {
            if (ModelState.IsValid)
            {
                string path = "";
                if (imgFile.FileName.Length > 0)
                {
                    path = "~/Images/" + Path.GetFileName(imgFile.FileName);
                    imgFile.SaveAs(Server.MapPath(path));
                }
                product.Image = path;
                db.products.Add(product);
                var categoryindb = db.categories.Single(c => c.CID == product.CID);
                categoryindb.Nun_of_products++;
                db.SaveChanges();
                return RedirectToAction("HomePage");
                
            }

            ViewBag.CID = new SelectList(db.categories, "CID", "CName", product.CID);
            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CID = new SelectList(db.categories, "CID", "CName", product.CID);
            return View(product);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,Image,Description,CID")] product product, HttpPostedFileBase imgFile)
        {
            if (ModelState.IsValid)
            {
                string path = "";
                if (imgFile.FileName.Length > 0)
                {
                    path = "~/Images/" + Path.GetFileName(imgFile.FileName);
                    imgFile.SaveAs(Server.MapPath(path));
                }
                product.Image = path;
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("HomePage");
            }
            ViewBag.CID = new SelectList(db.categories, "CID", "CName", product.CID);
            return View(product);
        }

        // GET: products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("HomePage");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
        
    }
}

Views/products/Create.cshtml
@model IAtaskTest.Models.product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "products", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imgFile" name="imgFile" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CID, "CID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "HomePage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/products/Delete.cshtml
@model IAtaskTest.Models.product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Image)" width="300" height="300" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category.CName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.CName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "HomePage")
        </div>
    }
</div>

Views/products/Details.cshtml
@model IAtaskTest.Models.product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Image)" width="300" height="300" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category.CName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.CName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
</p>

Views/products/Edit.cshtml
@model IAtaskTest.Models.product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "products", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imgFile" name="imgFile" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CID, "Category Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "HomePage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/products/HomePage.cshtml
@model IEnumerable<IAtaskTest.Models.product>

@{
    ViewBag.Title = "HomePage";
}

<h2>HomePage</h2>

<p>
    <a href="@Url.Action("Create", "products")" class="btn btn-primary" target="_blank">
        <span class="glyphicon glyphicon-plus"></span>
        New Product
    </a>
</p>

<p>
    @using (@Html.BeginForm())
    {
        @Html.TextBox("search") <input type="submit" value="search" />
    }
</p>
<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@Url.Content(item.Image)" alt="..." width="200" height="200">
                <div class="caption">
                    <h3>@item.Name</h3>
                    <p>...</p>
                    <p><a href="@Url.Action("Details", "products", new { id = item.Id})" class="btn btn-primary" role="button">More Info</a> </p>
                </div>
            </div>
        </div>

    }
</div>

Views/products/Index.cshtml
@model IEnumerable<IAtaskTest.Models.product>

@{
    ViewBag.Title = "HomePage";
}

<h2>HomePage</h2>

<p>
    <a href="@Url.Action("Create", "products")" class="btn btn-primary" target="_blank">
        <span class="glyphicon glyphicon-plus"></span>
        New Product
    </a>
</p>

<p>
    @using (@Html.BeginForm())
    {
        @Html.TextBox("search") <input type="submit" value="search" />
    }
</p>
<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@Url.Content(item.Image)" alt="..." width="200" height="200">
                <div class="caption">
                    <h3>@item.Name</h3>
                    <p>...</p>
                    <p><a href="@Url.Action("Details", "products", new { id = item.Id})" class="btn btn-primary" role="button">More Info</a> </p>
                </div>
            </div>
        </div>

    }